username       = "administrator@vsphere.local"
password       = "VMware1!"
vcenter        = "vcsa01.lab.local"
datacenter     = "DC01"
cluster        = ["CL01"]
esxihost       = ["esx01.lab.local"]
datastore      = ["datastore1"]
network        = ["VM Network"]
folder         = ["/DC01/vm/Packer"]
vsphereaccount = "vsphere.local\\Packer"
