variable "username" {}
variable "password" {}
variable "vcenter" {}
variable "datacenter" {}
variable "cluster" {}
variable "esxihost" {}
variable "datastore" {}
variable "network" {}
variable "folder" {}
variable "vsphereaccount" {}
